### ISSUE TITLE
FieldtypeSelectExtOption::getOptions

### ISSUE THREAD

**Issue by tiefenb** [kixe/FieldtypeSelectExtOption#10]
Error: Exception: Method FieldtypeSelectExtOption::getOptions does not exist or is not callable in this context (in /Applications/MAMP/htdocs/contenthub/wire/core/Wire.php line 519)

$shopsField = wire('fields')->get("shop_field");
$shopsField = $shopsField->type->getOptions($shopsField);

Is it possible to get all Options from an FieldtypeSelectExtOption? As same as in a FieldtypeSelect Field.

**Comment by kixe** [comment]
@tiefenb 
Please read the docs (README.md)
```
// assoc array (value => label) of all selectable options
$page->shop_field->options
// OR
$shopsField = wire('fields')->get("shop_field");
$shopsField = $shopsField->type->options($shopsField);
```
Use the support board for help
https://processwire.com/talk/topic/9320-fieldtype-select-external-option/

**Comment by kixe** [comment]
Fixed bug in function **options()** if argument is not an instance of field.
If you need to get options array from anywhere (not via page field value) use:
```
// since version 1.3.6
$xo = new FieldtypeSelectExtOption();
$options = $xo->options('shop_field'); // use field instance, name or id as argument
```

**Comment by tiefenb** [comment]
thx!
