### ISSUE TITLE
Warning: array_pop() expects parameter 1 to be array

### ISSUE THREAD

**Issue by tiefenb** [kixe/FieldtypeSelectExtOption#13]
I use a FieldtypeSelectExtOption field in a Repeater and get this error:

Warning: array_pop() expects parameter 1 to be array, string given in /var/www/html/site/modules/FieldtypeSelectExtOption/FieldtypeSelectExtOption.module on line 511

PHP 7.4.2
MySQL 5.7.29
PW: 3.0.152
Module Version 2.0.1

**Comment by tiefenb** [comment]
Changing the line 511 to this fixed it in the meanwhile:

if(!$module instanceof InputfieldHasArrayValue) {
			if(is_array($value)) {
				return $this->getSingleValue($field,array_pop($value));
			} else {
				return $this->getSingleValue($field,$value);
			}
		}

**Comment by kixe** [comment]
@tiefenb Thanks for reporting. I fixed this, but I couldn't figure out the reason for this issue. I use this fieldtype in repeaters as well, with several Inputfields and without any problems. Did you switch from another Filedtype to this one? Which Inputfieldtype do you use?

**FieldtypeMulti::loadPageField()** returns array or null - nothing else. Where did **wakeupValue()** get the value from?

**Comment by tiefenb** [comment]
@kixe Hmmm, I tried to reproduce the issue without the change, but know it works. I guess I switched from AsmSelect to Checkboxes. :-/
