### ISSUE TITLE
Warning: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by tiefenb** [kixe/FieldtypeSelectExtOption#14]
I get this since upgrade from PHP 8.0.x to 8.2.11:

Warning: Trying to access array offset on value of type bool in
/var/www/html/site/modules/FieldtypeSelectExtOption/FieldtypeSelectExtOption.module
on line
545

Any ideas?

**Comment by tiefenb** [comment]
I also get: FieldtypeSelectExtOption: FieldtypeSelectExtOption: Maximum number (500 < 1149) of selectable options exceeded. Use filter function in field settings to limit.

But I can't filter this down to 500 since I need all of the entries...

**Comment by kixe** [comment]
> I get this since upgrade from PHP 8.0.x to 8.2.11:
> 
> Warning: Trying to access array offset on value of type bool in /var/www/html/site/modules/FieldtypeSelectExtOption/FieldtypeSelectExtOption.module on line 545
> 
> Any ideas?

Checkout Version 2.1.2

**Comment by kixe** [comment]
> I also get: FieldtypeSelectExtOption: FieldtypeSelectExtOption: Maximum number (500 < 1149) of selectable options exceeded. Use filter function in field settings to limit.
> 
> But I can't filter this down to 500 since I need all of the entries...

500 is a lot. I do not want to change this. I have tried several browsers. The rendering gets slow beyond 500.
Fork the module and change the const to meet your needs.

```
	/**
	 * Max allowed number of options
	 * 
	 */
	const OPTIONSLIMIT = 500;
```

**Comment by tiefenb** [comment]
Thanks!
