### ISSUE TITLE
"Order by" does nothing until adding the ksort where it's commented out here?

### ISSUE THREAD

**Issue by chimmel** [kixe/FieldtypeSelectExtOption#15]
https://github.com/kixe/FieldtypeSelectExtOption/blob/c0910b0521a5fdc2b29f7a0c83e11eb60566a5a7/FieldtypeSelectExtOption.module#L337

Reinstating that line (sans "else ") seems to resolve it.

**Comment by kixe** [comment]
@chimmel 
Thanks for pointing on this. I pushed an update to fix. Please check and close.

**Comment by chimmel** [comment]
Thanks
