### ISSUE TITLE
Any option_output besides 'value' or 'id_of' results in field change

### ISSUE THREAD

**Issue by chimmel** [kixe/FieldtypeSelectExtOption#16]
Any value other than `value|id_of` for `option_output` field setting inevitably produces `ProcessPageAdd: Change:` even when no change has been made.

Removing `if ($field->option_output) $new->toString = $field->option_output;` from `getSingleValue()` prevents the message but doesn't change the `option_output`. Placing `return $new;` before it seems to work? Doesn't seem to many any difference other than that it doesn't change the `option_output` so it's moot in this case; changes are tracked as they should be.

Ultimately returning anything other than `$this->value` in `SelectExtOption` `toString()` results in this issue.

I've tried setting track changes to false, `setQuietly()` doesn't work.. nor does changing the value of `toString` in the `SelectExtOpt` object constructor data.

Thank you.

**Comment by chimmel** [comment]
Adding a formatValue method to the fieldtype returning $value->label overrides the issue.

```
/**
 * Format the given value for output and return a string of the formatted value
 * 
 * option_output issue override
 *
 * #pw-group-formatting
 * 
 * @param Page $page Page that the value lives on
 * @param Field $field Field that represents the value
 * @param string|int|object $value The value to format
 * @return mixed
 *
 */
public function ___formatValue(Page $page, Field $field, $value) {
	if ($field->option_output == 'id_of') return $value->id_of;
	if ($field->option_output == 'value') return $value->label;
}
```

**Comment by chimmel** [comment]
Sorry the above is based on the field's settings; this is more objective:
```
if ($field->option_output == $field->option_value) return $value->{$field->option_value};
if ($field->option_output == 'value') return $value->{$field->option_label};
```

**Comment by kixe** [comment]
This is a known issue. I finally added an internal function `getEqualValue()` as workaround to prevent `Page::trackChange()` triggered by `PageComparison::isEqual()` resulting in a message even if nothing has changed due to strict object comparison (ProcessWire bug).

Please update to 2.1.4. Thanks.
