### ISSUE TITLE
Accessing page field values without using get method - errors

### ISSUE THREAD

**Issue by chimmel** [kixe/FieldtypeSelectExtOption#18]
In Tracy Debugger per field of type in page editor:
`PHP Warning: Undefined property: ProcessWire\ListPage::$layout in [.../FieldtypeSelectExtOption/FieldtypeSelectExtOption.module:561]`

When a field value is changed, error in RequestInfoPanel:
`ErrorException: Object of class ProcessWire\SelectExtOption could not be converted to int in /pw/site/modules/FieldtypeSelectExtOption/FieldtypeSelectExtOption.module:617`

Using `echo $page->get('layout');` works but `$page->layout` results in said errors. Trying one and then the other results in an incorrect value output secondly?

**Comment by kixe** [comment]
Fixed. Please Update to 2.1.5 and check.

**Comment by chimmel** [comment]
Thank you
