### ISSUE TITLE
PR for Custom SQL Query for Label?

### ISSUE THREAD

**Issue by thomasaull** [kixe/FieldtypeSelectExtOption#8]
For a recent client project I extended this module. I wanted to show data in the label which is not present in the table itself, so I made an input field for a custom SQL Query to fetch data from another database table to display as the label. Is this extension of interest for the core module. In this case I'd prepare a pull request.

<img width="1424" alt="grafik" src="https://user-images.githubusercontent.com/227756/29769175-7a972902-8be9-11e7-8b93-c1ab8e1d36c1.png">

**Comment by kixe** [comment]
@thomasaull 
Thanks for effort and input. I decided not to implement this extension. Function label is hookable. Inspired by your needs I changed the arguments of `___label()` in latest commit, which allows you to modify it with a small hook in your **ready.php**
```
/**
 * hook in FieldtypeSelectExtOption::label
 * FieldtypeSelectExtOption >= 1.3.5 required
 */
wire()->addHookAfter('FieldtypeSelectExtOption::label', null, function ($e) {
    $field = $e->arguments[3];
    if ($field->id != 176) return; // quick exit if fields ID doesn't match
    $query = wire('database')->prepare("SELECT product_description_name FROM product_description WHERE product_id = {$e->arguments[1]}");
    wire('database')->execute($query);
    $e->return = $query->fetch();
});
```
Pull all relevant vars from arguments of the hooked function
```
wire()->addHookAfter('FieldtypeSelectExtOption::label', null, function ($e) {
    $optLabel = $e->arguments[0];
    $optValue = $e->arguments[1];
    $page = $e->arguments[2];
    $field = $e->arguments[3];
});
```

**Comment by thomasaull** [comment]
That's perfectly fine! Thanks for the hook :)
