### ISSUE TITLE
Error in /processwire/setup/sessions-db/  after using FieldtypeSelectExtOption

### ISSUE THREAD

**Issue by tiefenb** [kixe/FieldtypeSelectExtOption#9]
I get an error now in my session-db module page:

Catchable fatal error: Argument 1 passed to ProcessWire\ProcessController::getProcessMethodName() must be an instance of ProcessWire\Process, instance of FieldtypeSelectExtOption given, called in /srv/processwire/html/wire/core/ProcessController.php on line 241 and defined in /srv/processwire/html/wire/core/ProcessController.php on line 193
Recoverable Fatal Error: Argument 1 passed to ProcessWire\ProcessController::getProcessMethodName() must be an instance of ProcessWire\Process, instance of FieldtypeSelectExtOption given, called in /srv/processwire/html/wire/core/ProcessController.php on line 241 and defined (line 193 of /srv/processwire/html/wire/core/ProcessController.php) 

This error message was shown because: site is in debug mode. ($config->debug = true; => /site/config.php). Error has been logged.

**Comment by kixe** [comment]
Cannot reproduce using PW v3.0.73, FieldtypeSelectExtOption v1.3.5, ProcessSessionDB v0.0.3
Please give more detailed information:
PW and Module Version?
Happened the error after installing, updating ... ?
Any hooks? API calls?
Field settings?

**Comment by kixe** [comment]
no feedback. ticket closed.

**Comment by tiefenb** [comment]
Sorry for the late feedback:

The error happens only on one page in the admin panel - in the Sessions DB Page: /processwire/setup/sessions-db/

The Module is installed and used by many pages on our website.

Current Setup:
PW: 3.0.82
Module Version: 1.3.6
PHP: 7.1.8 (happens also in 7.0.22)

![bildschirmfoto 2017-11-06 um 12 52 59](https://user-images.githubusercontent.com/488163/32439988-7e85a68a-c2f1-11e7-895c-f82e0b3c84a6.png)

**Comment by tiefenb** [comment]
If you want to look closer into our stack, we can also setup an skype call where we can make a screensharing session. You can message me on twitter: https://twitter.com/tiefenb

**Comment by kixe** [comment]
This Error cannot be caused by the Module FieldtypeSelectExtOption. It looks more like a wrong field setting or Database Manipulation.
1. Go here: **Admin > Setup > Sessions > Edit**
2. Check the field value of '**Process**'.
3. Value should be '**ProcessSessionDB**' and not **'0'** or anything else.

**Comment by tiefenb** [comment]
The problem is, that error occurs on this page. So I can't access it.
Also deinstalling and new installing the Session module doesn't help.

<img width="1400" alt="bildschirmfoto 2017-11-07 um 07 52 12" src="https://user-images.githubusercontent.com/488163/32480761-a3c987b4-c390-11e7-9c93-689f23ee4d3d.png">

**Comment by tiefenb** [comment]
This happens, when I delete the FieldtypeSelectExtOption Module Folder:

<img width="1391" alt="bildschirmfoto 2017-11-07 um 07 54 26" src="https://user-images.githubusercontent.com/488163/32480849-0710396c-c391-11e7-9f0f-e328412a912d.png">

**Comment by kixe** [comment]
Sorry I wasn't clear enough I didn't mean **go to this page!**
I wanted to say **go to the EDIT area of this page!**
In the page tree under: **Admin > Setup > Sessions**

After clicking the green EDIT button I guess you will see something like this, which is wrong:
![bildschirmfoto 2017-11-06 um 20 56 32](https://user-images.githubusercontent.com/4683120/32485724-ade6dfe4-c3a4-11e7-8d33-2701b1648a9b.jpg)
Select the right process for this page
![bildschirmfoto 2017-11-06 um 20 56 54](https://user-images.githubusercontent.com/4683120/32486019-a940cb34-c3a5-11e7-966e-ee19dafbbb43.jpg)

**Comment by tiefenb** [comment]
Ah - great this fixed the issue. THX!
